name = "coreui"
compatibility_date = "2022-06-03"
type = "javascript"

workers_dev = true

main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[env.production]
workers_dev = false
route = "https://coreui-sf.pkasila.net/*"
